kube-prometheus-stack:
  fullnameOverride: coralogix
  defaultRules:
    create: true
    rules:
      alertmanager: true
  alertmanager:
    enabled: true 
    tplConfig: true
    alertmanagerSpec:
      alertmanagerConfigSelector: 
        matchLabels:
# ????? any alertmanagerconfigs i should supply ? 