kube-prometheus-stack:
  fullnameOverride: prometheus
  defaultRules:
    create: true
    rules:
      prometheusOperator: true
  kubelet: 
    enabled: true
  prometheusOperator:
    enabled: true
    prometheusConfigReloader:
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 200Mi
    serviceMonitor: 
      interval: "20s"
    admissionWebhooks:
      enabled: true
      patch:
        enabled: true
      certManager:
        enabled: true 
    kubeletService:
      enabled: true
    logFormat: json
    resources:
      limits:
        cpu: 200m
        memory: 450Mi
    requests:
      cpu: 100m
      memory: 450Mi
  additionalPrometheusRulesMap:
    monitoring:
      groups:
      - name: prometheus-operator-rules
        rules: 
        - alert: PrometheusOperatorRuleValidationErrors
          annotations: 
            message: |
              This alert checks if there were rule validation errors,
              which means someone tried to edit a prometheusrule in an invalid way. 
          expr: rate(prometheus_operator_rule_validation_errors_total[5m]) > 0
          labels:
            severity: warning