
name: Fluentd-HTTP-Chart

on:
  push:
    branches: master
    paths:
    - 'fluentd/http/**'

env:
  CHART_VERSION: $(yq eval '.version' fluentd/http/Chart.yaml)
  CHART_NAME: fluentd-http
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/
  ARTIFACTORY_USERNAME: integrations-actions
  CXINTEGRATIONS_CLI_PATH: cxtool

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Setup Helm Repo
        run: |
          helm repo add coralogix-charts-virtual ${{ env.ARTIFACTORY_URL }}coralogix-charts-virtual --username ${{ env.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }}
          helm repo update
          helm dependency build ./fluentd/http/
          cd fluentd/http
          helm package .
      -
        name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2.1.0
        with:
          version: 2.12.1
      -
        name: use-jfrog-cli
        run: |
          cd fluentd/http
          jfrog rt upload --access-token ${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }} "${{ env.CHART_NAME }}-*.tgz" coralogix-charts --url ${{ env.ARTIFACTORY_URL }}    
      -
        name: Generate Integrations Manifests
        run: |
          cd ${{ env.CXINTEGRATIONS_CLI_PATH }}
          ./cx-integrations generate ${{ env.CHART_NAME }} --outputdir manifests
          git add ./manifests/${{ env.CHART_NAME }}-manifests.yaml 
          git commit -m "Update fluentd-http manifests for manual deploy"
          git push